(function() {var implementors = {};
implementors['libc'] = [];implementors['openssl'] = [];implementors['simple_stream'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.SimpleFrame.html' title='simple_stream::frame::SimpleFrame'>SimpleFrame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.WebSocketFrame.html' title='simple_stream::frame::WebSocketFrame'>WebSocketFrame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.Checksum32Frame.html' title='simple_stream::frame::Checksum32Frame'>Checksum32Frame</a>",];implementors['simple_stream'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.SimpleFrame.html' title='simple_stream::frame::SimpleFrame'>SimpleFrame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.WebSocketFrame.html' title='simple_stream::frame::WebSocketFrame'>WebSocketFrame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='simple_stream/frame/struct.Checksum32Frame.html' title='simple_stream::frame::Checksum32Frame'>Checksum32Frame</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
